# Generated by Django 5.1.4 on 2025-01-25 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_rename_profile_user_uprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='user',
            field=models.CharField(default='buyer', max_length=20),
        ),
    ]
