# Generated by Django 5.1.4 on 2025-01-25 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_product_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='image',
        ),
        migrations.AddField(
            model_name='product',
            name='profile',
            field=models.ImageField(default='', upload_to='profile/'),
        ),
    ]
