# Generated by Django 5.1.4 on 2025-01-27 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_remove_product_image_product_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='profile',
        ),
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(default='', upload_to='product/'),
        ),
    ]
